service: cognito-oauth
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  profile: sdom
  region: me-central-1
  stage: dev
  environment:
    OIDC_ISSUER: ${env:OIDC_ISSUER, ''}
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN, ''}

plugins:
  - serverless-offline
  - serverless-export-env


functions:
  userInfo:
    handler: src/user-info.handler
    name: oauth-user-info-${self:provider.stage}
    role: !GetAtt LambdaS3AccessRole.Arn
    events:
      - httpApi:
          path: /user_info
          method: get
          authorizer:
            type: aws_iam

  authorize:
    handler: src/authorize.handler
    events:
      - httpApi:
          path: /authorize
          method: get

  token:
    handler: src/token.handler
    environment:
      SECRET_S3_BUCKET: !Ref SecureS3Bucket
    role: !GetAtt LambdaS3AccessRole.Arn
    events:
      - httpApi:
          path: /token
          method: get

  jwks:
    handler: src/jwks.handler
    events:
      - http:
          path: .well-known/jwks.json
          method: get

resources:
  - ${file(resources/cognito/client.yml)}
  - ${file(resources/cognito/idp.yml)}
  - ${file(resources/cognito/userpool.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/iam.yml)}
